###############################################################################
#
# Makefile for a script, project 6
#
# Students:
# Anna Seliverstov, ID 317339505, anna.seliverstov@mail.huji.ac.il
#
###############################################################################


all:
	chmod a+x Assembler

